version: '3.8'

services:
    rclone-sa-autoswap:
        image: dantebarba/rclone-sa-autoswap:latest
        container_name: rclone-sa-autoswap
        volumes:
            - path to rclone conf:/config/rclone.conf
        environment:
            CRON: '0 * * * *' # will renew the SA number once every hour
            MAX_NUMBER: 4 # the number of SAs you generated
            PREFIX: '/config/sa/gdrive-sa-' # the prefix with path included before the SA Number.
            # SAs should be named with the following schema: my-sa-{number}.json where number is the SA designated number.
            # this number should be sequential, from 1 to n.
        
